# Generated by Django 3.2.8 on 2021-11-16 22:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('column_index', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('level_index', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=3, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True)),
                ('type', models.CharField(choices=[('storage', 'Przechowywanie'), ('receiving', 'Przyjmowanie'), ('shipping', 'Wysyłka')], default='storage', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_number', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=50, unique=True)),
                ('columns', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('levels', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='warehouse.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Shelves',
            },
        ),
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(default='16/11/2021', max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='warehouse.product')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='parent_shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='warehouse.shelf'),
        ),
    ]
