# Generated by Django 3.2.8 on 2021-11-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlocation',
            name='lot_number',
            field=models.CharField(default='17/11/2021', max_length=10),
        ),
    ]
