# Generated by Django 3.2.8 on 2021-10-17 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not defined', max_length=50, unique=True)),
                ('rows', models.IntegerField(default=1)),
                ('cols', models.IntegerField(default=1)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='warehouse.warehouse')),
            ],
        ),
    ]
