# Generated by Django 3.2.8 on 2021-10-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelf',
            old_name='cols',
            new_name='columns',
        ),
        migrations.RenameField(
            model_name='shelf',
            old_name='rows',
            new_name='levels',
        ),
    ]
