# Generated by Django 3.2.8 on 2021-11-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='type',
            field=models.CharField(choices=[('storage', 'Przechowywanie'), ('receiving', 'Przyjmowanie'), ('shipping', 'Wysyłka')], default='storage', max_length=20),
        ),
    ]
