# Generated by Django 3.2.8 on 2021-11-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_productlocation_lot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlocation',
            name='lot_number',
            field=models.CharField(default='19/11/2021', max_length=10),
        ),
    ]
