# Generated by Django 3.2.8 on 2021-10-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
