# Generated by Django 3.2.8 on 2021-10-19 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20211018_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='shelf_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
