# Generated by Django 3.2.8 on 2021-11-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20211124_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='productlocation',
            name='lot_number',
            field=models.CharField(default='25/11/2021', max_length=10),
        ),
    ]
