# Generated by Django 3.2.8 on 2021-10-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_auto_20211017_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
