# Generated by Django 3.2.8 on 2021-10-18 11:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_warehouse_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rows', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('cols', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='warehouse.warehouse')),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='parent_rack',
        ),
        migrations.DeleteModel(
            name='Rack',
        ),
        migrations.AddField(
            model_name='location',
            name='parent_shelf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='warehouse.shelf'),
            preserve_default=False,
        ),
    ]
