# Generated by Django 3.2.8 on 2021-10-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20211018_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelf',
            options={'verbose_name_plural': 'Shelves'},
        ),
    ]
