# Generated by Django 3.2.8 on 2021-11-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20211127_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='max_load',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productlocation',
            name='lot_number',
            field=models.CharField(default='28/11/2021', max_length=10),
        ),
    ]
