# Generated by Django 3.2.8 on 2021-12-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_alter_productlocation_lot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlocation',
            name='lot_number',
            field=models.CharField(default='01/12/2021', max_length=10),
        ),
    ]
