# Generated by Django 3.2.8 on 2021-11-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_goodsreceivednote'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='document_type',
            field=models.CharField(default='GRN', max_length=3),
        ),
    ]
