# Generated by Django 3.2.8 on 2021-11-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='email',
            field=models.CharField(default='admn', max_length=100),
            preserve_default=False,
        ),
    ]
