# Generated by Django 3.2.8 on 2021-11-22 21:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_contractor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
