# Generated by Django 3.2.8 on 2021-11-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20211122_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='goodsissuenote',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.contractor'),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.contractor'),
        ),
    ]
