# Generated by Django 3.2.8 on 2021-11-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_productlocation_lot_number'),
        ('documents', '0007_auto_20211122_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warehouse.warehouse'),
        ),
    ]
