# Generated by Django 3.2.8 on 2021-11-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_productlocation_lot_number'),
        ('documents', '0008_alter_document_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='document_type',
            field=models.CharField(default='PZ', max_length=3),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='warehouse.location'),
        ),
    ]
