# Generated by Django 3.2.8 on 2021-11-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_internalgoodsreceivednote'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsissuenote',
            name='document_type',
            field=models.CharField(default='WZ', max_length=3),
        ),
        migrations.AddField(
            model_name='internalgoodsissuenote',
            name='document_type',
            field=models.CharField(default='RW', max_length=3),
        ),
    ]
