# Generated by Django 3.2.8 on 2021-11-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20211128_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdocument',
            name='lot_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
