# Generated by Django 3.2.8 on 2021-11-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_alter_productlocation_lot_number'),
        ('documents', '0012_productdocument_lot_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTransfer',
            fields=[
                ('productdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.productdocument')),
                ('location_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='warehouse.location')),
            ],
            bases=('documents.productdocument',),
        ),
        migrations.CreateModel(
            name='InterBranchTransferPlus',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('document_type', models.CharField(default='MM+', max_length=3)),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
        migrations.CreateModel(
            name='InterBranchTransferMinus',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('document_type', models.CharField(default='MM-', max_length=3)),
                ('target_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('documents.document',),
        ),
    ]
