# Generated by Django 3.2.8 on 2021-11-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_interbranchtransferminus_interbranchtransferplus_producttransfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttransfer',
            old_name='location_source',
            new_name='location_target',
        ),
    ]
