# Generated by Django 3.2.8 on 2021-12-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_alter_productlocation_lot_number'),
        ('documents', '0014_rename_location_source_producttransfer_location_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransfer',
            name='location_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.location'),
        ),
    ]
